name: Push Docker Image to ECR Repo
on:
  push:
    branches:
      - main

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
        
        # Public ECR Available in us-east-1
      - name: Login to Amazon Public ECR
        run: |
          aws ecr-public get-login-password --region ${{ secrets.AWS_REGION }} | \
          docker login --username AWS --password-stdin public.ecr.aws

      - name: Build, tag and push to Public ECR
        env:
          ECR_REPO_NAME: ${{ secrets.ECR_REPO_NAME }}
          IMAGE_TAG: msfrontend
        run: |
          PUBLIC_ECR_URI="public.ecr.aws/e3m0x0s5/microservices"
          docker build -t $PUBLIC_ECR_URI/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $PUBLIC_ECR_URI/$ECR_REPOSITORY:$IMAGE_TAG


             
                


